#!/usr/bin/env python3
"""Check whether tactile HDF5 labels are reproducible by action replay.

The tactile shards were generated by forcing recorded MuJoCo states and calling
sim.forward(). This script compares that path against stepping the recorded
actions from the same initial state.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import h5py
import numpy as np


ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT / "robosuite"), str(ROOT)]

import dexmimicgen  # noqa: E402,F401
from tactile_recollect.env import make_env_from_env_args, read_tactile_image  # noqa: E402


def reset_to(env, state: dict) -> None:
    if "model" in state:
        ep_meta = json.loads(state["ep_meta"]) if state.get("ep_meta") else {}
        if hasattr(env, "set_ep_meta"):
            env.set_ep_meta(ep_meta)
        elif hasattr(env, "set_attrs_from_ep_meta"):
            env.set_attrs_from_ep_meta(ep_meta)
        env.reset()
        xml = env.edit_model_xml(state["model"])
        env.reset_from_xml_string(xml)
        env.sim.reset()
    if "states" in state:
        env.sim.set_state_from_flattened(state["states"])
        env.sim.forward()
    if hasattr(env, "update_state"):
        env.update_state()
    elif hasattr(env, "update_sites"):
        env.update_sites()


def find_demo_group(shard_dir: Path, demo_key: str):
    for shard_path in sorted(shard_dir.glob("*.hdf5")):
        f = h5py.File(shard_path, "r")
        if f"data/{demo_key}" in f:
            return f, f[f"data/{demo_key}"], shard_path
        f.close()
    raise KeyError(f"{demo_key} not found in {shard_dir}")


def q(values, qs=(50, 90, 95, 99, 100)):
    values = np.asarray(values, dtype=np.float64)
    if values.size == 0:
        return "empty"
    parts = []
    for pct in qs:
        parts.append(f"p{pct}={np.percentile(values, pct):.6g}")
    return " ".join(parts)


def frame_max_abs(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    n = min(len(a), len(b))
    if n == 0:
        return np.asarray([], dtype=np.float32)
    return np.max(np.abs(a[:n] - b[:n]), axis=tuple(range(1, a.ndim)))


def contact_mask(x: np.ndarray, threshold: float) -> np.ndarray:
    return np.max(x, axis=tuple(range(1, x.ndim))) > threshold


def summarize_pair(name: str, a: np.ndarray, b: np.ndarray, threshold: float) -> None:
    err = frame_max_abs(a, b)
    am = np.max(a[: len(err)], axis=tuple(range(1, a.ndim))) if len(err) else []
    bm = np.max(b[: len(err)], axis=tuple(range(1, b.ndim))) if len(err) else []
    ca = contact_mask(a[: len(err)], threshold) if len(err) else []
    cb = contact_mask(b[: len(err)], threshold) if len(err) else []
    mismatch = float(np.mean(ca != cb)) if len(err) else float("nan")
    print(f"  {name}:")
    print(f"    frame_max_abs_err: {q(err)} mean={float(np.mean(err)) if len(err) else float('nan'):.6g}")
    print(f"    max(a): {q(am)}")
    print(f"    max(b): {q(bm)}")
    print(f"    contact_mismatch@{threshold:g}: {mismatch:.3f}")


def run_demo(env, raw_group, tactile_group, demo_key: str, max_steps: int, threshold: float) -> None:
    states = raw_group["states"][:]
    actions = raw_group["actions"][:].astype(np.float32)
    h5_tactile = tactile_group["obs/robot0_tactile"][:]
    model = raw_group.attrs["model_file"]
    ep_meta = raw_group.attrs.get("ep_meta", None)
    t = min(len(states), len(actions), len(h5_tactile), max_steps or len(states))
    states = states[:t]
    actions = actions[:t]
    h5_tactile = h5_tactile[:t]

    forced = np.zeros_like(h5_tactile)
    reset_to(env, {"model": model, "states": states[0], "ep_meta": ep_meta})
    for i in range(t):
        reset_to(env, {"states": states[i]})
        forced[i] = read_tactile_image(env)

    rollout = np.zeros_like(h5_tactile)
    rollout_states = np.zeros_like(states)
    reset_to(env, {"model": model, "states": states[0], "ep_meta": ep_meta})
    rollout[0] = read_tactile_image(env)
    rollout_states[0] = env.sim.get_state().flatten()
    for i in range(1, t):
        env.step(actions[i - 1])
        rollout[i] = read_tactile_image(env)
        rollout_states[i] = env.sim.get_state().flatten()

    state_err = frame_max_abs(rollout_states, states)
    shifted_tactile_err = frame_max_abs(rollout[1:], h5_tactile[1:])
    print(f"\n[{demo_key}] T_checked={t}")
    print(f"  action_shape={actions.shape} state_shape={states.shape} tactile_shape={h5_tactile.shape}")
    print(f"  forced_total_max={float(forced.max()):.6g} h5_total_max={float(h5_tactile.max()):.6g} rollout_total_max={float(rollout.max()):.6g}")
    summarize_pair("forced[t] vs h5[t]", forced, h5_tactile, threshold)
    summarize_pair("rollout[t] vs h5[t]", rollout, h5_tactile, threshold)
    summarize_pair("rollout[t+1 after action[t]] vs h5[t+1]", rollout[1:], h5_tactile[1:], threshold)
    print(f"  rollout_state_vs_recorded_state frame_max_abs: {q(state_err)} mean={float(np.mean(state_err)):.6g}")
    if len(shifted_tactile_err):
        worst = np.argsort(shifted_tactile_err)[-5:][::-1] + 1
        print("  worst_shifted_frames:")
        for idx in worst:
            print(
                f"    frame={int(idx)} h5_max={float(h5_tactile[idx].max()):.6g} "
                f"rollout_max={float(rollout[idx].max()):.6g} "
                f"err={float(np.max(np.abs(rollout[idx] - h5_tactile[idx]))):.6g}"
            )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--raw-h5", default=str(ROOT / "datasets/generated/two_arm_three_piece_assembly.hdf5"))
    parser.add_argument(
        "--shard-dir",
        default=str(
            ROOT
            / "datasets/generated_tactile_proud2mm_shards/20260724_073329/two_arm_three_piece_assembly"
        ),
    )
    parser.add_argument("--demos", nargs="+", default=["demo_0", "demo_1", "demo_2", "demo_3", "demo_4"])
    parser.add_argument("--max-steps", type=int, default=180)
    parser.add_argument("--contact-threshold", type=float, default=1e-3)
    args = parser.parse_args()

    raw_h5 = Path(args.raw_h5)
    shard_dir = Path(args.shard_dir)
    with h5py.File(raw_h5, "r") as raw_file:
        env = make_env_from_env_args(raw_file["data"].attrs["env_args"])
        for demo_key in args.demos:
            tactile_file = None
            try:
                tactile_file, tactile_group, shard_path = find_demo_group(shard_dir, demo_key)
                print(f"\n=== {demo_key} from {shard_path.name} ===")
                run_demo(
                    env,
                    raw_file[f"data/{demo_key}"],
                    tactile_group,
                    demo_key,
                    args.max_steps,
                    args.contact_threshold,
                )
            finally:
                if tactile_file is not None:
                    tactile_file.close()


if __name__ == "__main__":
    main()
